//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define IDEDIT                          3
#define IDAutoMap                       3
#define ID_RemoveListener               3
#define IDC_Delete                      4
#define ID_RemoveBroadcaster            4
#define ID_BUTTON_AddBroadcaster        5
#define ID_BUTTON_AddBroadcaster2       6
#define ID_BUTTON_AddListener           6
#define IDD_DIALOG_Page                 103
#define IDD_DIALOG_EditFXParam          115
#define IDD_DIALOG_RemapAutoFX          117
#define IDD_DIALOG_Advanced             119
#define IDD_AutoOrLearn                 121
#define IDD_DIALOG_Broadcast            123
#define IDD_SURFACEEDIT_CSI             265
#define IDD_DIALOG_MidiSurface          268
#define IDD_DIALOG_OSCSurface           269
#define IDD_DIALOG_PageSurface          270
#define IDC_EDIT_PageName               1003
#define IDC_COMBO_ZoneTemplates         1017
#define IDC_COMBO_FXZoneTemplates       1018
#define IDC_COMBO_SurfaceTemplate       1019
#define IDC_COMBO_MidiIn                1020
#define IDC_COMBO_MidiOut               1021
#define IDC_EDIT_MidiSurfaceName        1022
#define IDC_LIST_Pages                  1024
#define IDC_BUTTON_AddPage              1025
#define IDC_BUTTON_EditPage             1026
#define IDC_BUTTON_RemovePage           1027
#define IDC_LIST_PageSurfaces           1028
#define IDC_BUTTON_AddPageSurface       1029
#define IDC_BUTTON_EditPageSurface      1030
#define IDC_BUTTON_RemovePageSurface    1031
#define IDC_LIST_Surfaces               1032
#define IDC_BUTTON_AddMidiSurface       1033
#define IDC_BUTTON_EditSurface          1034
#define IDC_BUTTON_RemoveSurface        1035
#define IDC_BUTTON_AddOSCSurface        1036
#define IDC_BUTTON_Advanced             1037
#define IDC_EDIT_OSCSurfaceName         1039
#define IDC_EDIT_OSCRemoteDeviceIP      1041
#define IDC_EDIT_OSCOutPort             1043
#define IDC_EDIT_OSCInPort              1045
#define IDC_EDIT_NumChannels            1085
#define IDC_EDIT_ChannelOffset          1088
#define IDC_COMBO_PageSurface           1091
#define IDC_CHECK_SynchPages            1093
#define IDC_CHECK_ScrollLink            1094
#define IDC_CHECK_ScrollSynch           1096
#define IDC_RADIO_MCP                   1097
#define IDC_RADIO_TCP                   1098
#define IDC_PARAM_LIST                  1099
#define IDSAVE                          1100
#define IDC_FXNAME                      1101
#define IDC_EDIT_FXAlias                1102
#define IDC_BUTTONUP                    1103
#define IDC_BUTTONDOWN                  1104
#define IDC_EditSteps1                  1107
#define IDC_PickSteps1                  1108
#define IDC_EditSteps2                  1109
#define IDC_PickSteps2                  1110
#define IDC_EditSteps3                  1111
#define IDC_PickSteps3                  1112
#define IDC_Group1                      1137
#define IDC_Group2                      1138
#define IDC_AllParams                   1139
#define IDC_GroupFXParam1               1140
#define IDC_FXParamNumEdit1             1141
#define IDC_PickWidgetType1             1142
#define IDC_PickRingStyle1              1143
#define IDC_FixedTextDisplayPickRow1    1144
#define IDC_FixedTextDisplayPickRow2    1145
#define IDC_FixedTextDisplayPickRow3    1146
#define IDC_GroupFixedTextDisplay1      1148
#define IDC_FXParamNameEdit1            1149
#define IDC_FXParamValueDisplayPickRow1 1160
#define IDC_FXParamValueDisplayPickRow2 1161
#define IDC_FXParamValueDisplayPickRow3 1162
#define IDC_FXParamValueDisplayPickFont1 1163
#define IDC_FXParamValueDisplayPickFont2 1164
#define IDC_FXParamValueDisplayPickFont3 1165
#define IDC_FixedTextDisplayPickFont1   1166
#define IDC_FixedTextDisplayPickFont2   1167
#define IDC_GroupFXParam2               1168
#define IDC_GroupFXParamValueDisplay1   1169
#define IDC_FXParamNumEdit2             1170
#define IDC_FixedTextDisplayPickFont3   1171
#define IDC_FXParamRingColor1           1173
#define IDC_FXParamIndicatorColor1      1174
#define IDC_FXParamRingColor2           1175
#define IDC_FXParamIndicatorColor2      1176
#define IDC_FXParamRingColor3           1177
#define IDC_FXParamIndicatorColor3      1178
#define IDC_FixedTextDisplayForegroundColor1 1179
#define IDC_FixedTextDisplayForegroundColor2 1180
#define IDC_FixedTextDisplayForegroundColor3 1181
#define IDC_FixedTextDisplayBackgroundColor1 1182
#define IDC_FixedTextDisplayBackgroundColor2 1183
#define IDC_FixedTextDisplayBackgroundColor3 1184
#define IDC_FXParamDisplayForegroundColor1 1185
#define IDC_FXParamDisplayForegroundColor2 1186
#define IDC_FXParamDisplayForegroundColor3 1187
#define IDC_FXParamDisplayBackgroundColor1 1188
#define IDC_PickWidgetType2             1189
#define IDC_PickRingStyle2              1190
#define IDC_FXParamDisplayBackgroundColor2 1191
#define IDC_FXParamDisplayBackgroundColor3 1192
#define IDC_GroupFixedTextDisplay2      1195
#define IDC_FXParamNameEdit2            1196
#define IDC_FixedTextDisplayFontLabel1  1199
#define IDC_FixedTextDisplayFontLabel2  1200
#define IDC_FixedTextDisplayFontLabel3  1201
#define IDC_FXParamValueDisplayFontLabel1 1202
#define IDC_FXParamValueDisplayFontLabel2 1203
#define IDC_FXParamValueDisplayFontLabel3 1204
#define IDC_FXParamRingColorBox1        1205
#define IDC_FXParamRingColorBox2        1206
#define IDC_FXParamRingColorBox3        1207
#define IDC_FXParamIndicatorColorBox1   1208
#define IDC_FXParamIndicatorColorBox2   1209
#define IDC_FXParamIndicatorColorBox3   1210
#define IDC_FXFixedTextDisplayForegroundColorBox1 1211
#define IDC_FXFixedTextDisplayForegroundColorBox2 1212
#define IDC_FXFixedTextDisplayForegroundColorBox3 1213
#define IDC_FXFixedTextDisplayBackgroundColorBox1 1214
#define IDC_GroupFXParamValueDisplay2   1215
#define IDC_FXFixedTextDisplayBackgroundColorBox2 1216
#define IDC_FXFixedTextDisplayBackgroundColorBox3 1217
#define IDC_FXParamValueDisplayBackgroundColorBox1 1218
#define IDC_FXParamValueDisplayBackgroundColorBox2 1219
#define IDC_FXParamValueDisplayBackgroundColorBox3 1220
#define IDC_FXParamValueDisplayForegroundColorBox1 1221
#define IDC_FXParamValueDisplayForegroundColorBox2 1222
#define IDC_FXParamValueDisplayForegroundColorBox3 1223
#define IDC_StepsPromptGroup2           1224
#define IDC_StepsPromptGroup3           1225
#define IDC_StepsPromptGroup1           1231
#define IDC_AdvancedGroup1              1233
#define IDC_Group3                      1234
#define IDC_GroupFXParam3               1235
#define IDC_FXParamNumEdit3             1236
#define IDC_PickWidgetType3             1237
#define IDC_PickRingStyle3              1238
#define IDC_AdvancedGroup2              1239
#define IDC_AdvancedGroup3              1240
#define IDC_GroupFixedTextDisplay3      1243
#define IDC_FXParamNameEdit3            1244
#define IDC_LIST_Listeners              1246
#define IDC_LIST_Broadcasters           1247
#define IDC_EDIT_Delta                  1248
#define IDC_EDIT_RangeMin               1249
#define IDC_EDIT_RangeMax               1250
#define IDC_EDIT_DeltaValues            1251
#define IDC_EDIT_TickValues             1252
#define IDLearn                         1252
#define IDC_ListenCheckboxes            1253
#define IDC_CHECK_GoHome                1254
#define IDC_CHECK_SelectedTrackFX       1255
#define IDC_CHECK_Sends                 1256
#define IDC_CHECK_Receives              1257
#define IDC_CHECK_Learn                 1258
#define IDC_CHECK_AutoMap               1259
#define IDC_CHECK_FXMenu                1260
#define IDC_AddBroadcaster              1261
#define IDC_AddListener                 1262
#define IDC_GroupFXParamValueDisplay3   1263
#define IDC_CHECK_FocusedFX             1263
#define IDC_CHECK_FocusedFXParam        1264
#define IDC_CHECK_Custom                1265
#define IDC_CHECK_LocalFXSlot           1266
#define IDC_CHECK_Modifiers             1267

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1264
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
