//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define ID_RemoveListener               3
#define IDC_Delete                      4
#define ID_RemoveBroadcaster            4
#define ID_BUTTON_AddBroadcaster        5
#define IDC_EraseControl                5
#define ID_BUTTON_AddBroadcaster2       6
#define ID_BUTTON_AddListener           6
#define IDC_ExitNoSave                  6
#define IDD_DIALOG_Page                 103
#define IDD_DIALOG_LearnFX              117
#define IDD_DIALOG_LearnProperties      119
#define IDD_DIALOG_Broadcast            123
#define IDD_DIALOG_EditAdvanced         126
#define IDD_DIALOG_EditFXAlias          129
#define IDD_SURFACEEDIT_CSI             265
#define IDD_DIALOG_MidiSurface          268
#define IDD_DIALOG_OSCSurface           269
#define IDD_DIALOG_PageSurface          270
#define IDC_EDIT_PageName               1003
//#define IDC_COMBO_ZoneTemplates         1017
//#define IDC_COMBO_FXZoneTemplates       1018
//#define IDC_COMBO_SurfaceTemplate       1019
#define IDC_COMBO_MidiIn                1020
#define IDC_COMBO_MidiOut               1021
#define IDC_EDIT_MidiSurfaceName        1022
#define IDC_EDIT_MidiSurfaceRefreshRate 1023
#define IDC_LIST_Pages                  1024
#define IDC_EDIT_MidiSurfaceMaxSysExMessagesPerRun 1024
#define IDC_BUTTON_AddPage              1025
#define IDC_BUTTON_EditPage             1026
#define IDC_BUTTON_RemovePage           1027
#define IDC_LIST_PageSurfaces           1028
#define IDC_BUTTON_AddPageSurface       1029
#define IDC_BUTTON_EditPageSurface      1030
#define IDC_BUTTON_RemovePageSurface    1031
#define IDC_LIST_Surfaces               1032
#define IDC_BUTTON_AddMidiSurface       1033
#define IDC_BUTTON_EditSurface          1034
#define IDC_BUTTON_RemoveSurface        1035
#define IDC_BUTTON_AddOSCSurface        1036
#define IDC_BUTTON_Advanced             1037
#define IDC_EDIT_OSCSurfaceName         1039
#define IDC_EDIT_OSCRemoteDeviceIP      1041
#define IDC_EDIT_OSCOutPort             1043
#define IDC_EDIT_MaxPackets             1044
#define IDC_EDIT_OSCInPort              1045
#define IDC_EDIT_NumChannels            1085
#define IDC_EDIT_ChannelOffset          1088
#define IDC_COMBO_PageSurface           1091
#define IDC_CHECK_SynchPages            1093
#define IDC_CHECK_ScrollLink            1094
#define IDC_CHECK_ScrollSynch           1096
#define IDC_RADIO_MCP                   1097
#define IDC_RADIO_TCP                   1098
#define IDC_FXAlias                     1102
#define IDC_Params                      1105
#define IDC_Advanced                    1106
#define IDC_EditSteps                   1107
#define IDC_PickSteps                   1108
#define IDC_GroupFXWidget               1140
#define IDC_GroupFXAlias                1141
#define IDC_PickRingStyle               1143
#define IDC_GroupFixedTextDisplay       1148
#define IDC_FXParamNameEdit             1149
#define IDC_Edit_FixedTextDisplayTop    1150
#define IDC_GroupFixedTextDisplay2      1150
#define IDC_Edit_FixedTextDisplayBottom 1151
#define IDC_Edit_ParamValueDisplayTop   1152
#define IDC_Edit_ParamValueDisplayBottom 1153
#define IDC_ParamName                   1155
#define IDC_WidgetName                  1156
#define IDC_FXParamValueDisplayPickFont 1163
#define IDC_FixedTextDisplayPickFont    1166
#define IDC_GroupFXParamValueDisplay    1169
#define IDC_GroupFXParamValues          1170
#define IDC_FXParamRingColor            1173
#define IDC_FXParamIndicatorColor       1174
#define IDC_FixedTextDisplayForegroundColor 1179
#define IDC_FixedTextDisplayBackgroundColor 1182
#define IDC_FXParamDisplayForegroundColor 1185
#define IDC_FXParamDisplayBackgroundColor 1188
#define IDC_Save                        1190
#define IDC_Unassign                    1191
#define IDC_FixedTextDisplayFontLabel   1199
#define IDC_FXParamValueDisplayFontLabel 1202
#define IDC_FXParamRingColorBox         1205
#define IDC_FXParamIndicatorColorBox    1208
#define IDC_FXFixedTextDisplayForegroundColorBox 1211
#define IDC_FXFixedTextDisplayBackgroundColorBox 1214
#define IDC_FXParamValueDisplayBackgroundColorBox 1218
#define IDC_FXParamValueDisplayForegroundColorBox 1221
#define IDC_FixedTextDisplayTopLabel    1226
#define IDC_FixedTextDisplayBottomLabel 1227
#define IDC_ParamValueDisplayTopLabel   1228
#define IDC_ParamValueDisplayBottomLabel 1229
#define IDC_StepsPromptGroup            1231
#define IDC_LIST_Listeners              1246
#define IDC_LIST_Broadcasters           1247
#define IDC_EDIT_Delta                  1248
#define IDC_EDIT_RangeMin               1249
#define IDC_EDIT_RangeMax               1250
#define IDC_EDIT_DeltaValues            1251
#define IDC_EDIT_TickValues             1252
#define IDC_ListenCheckboxes            1253
#define IDC_CHECK_GoHome                1254
#define IDC_CHECK_SelectedTrackFX       1255
#define IDC_CHECK_Sends                 1256
#define IDC_CHECK_Receives              1257
#define IDC_CHECK_FXMenu                1260
#define IDC_AddBroadcaster              1261
#define IDC_AddListener                 1262
#define IDC_CHECK_FocusedFX             1263
#define IDC_CHECK_FocusedFXParam        1264
#define IDC_CHECK_LocalFXSlot           1266
#define IDC_CHECK_Modifiers             1267
#define IDC_CHECK_ShowRawInput          1268
#define IDC_CHECK_ShowInput             1269
#define IDC_CHECK_ShowOutput            1270
#define IDC_CHECK_WriteFXParams         1271
#define IDC_COMBO_Type                  1275
#define IDC_AcceleratedTickValuesLabel  1277
#define IDC_AcceleratedDeltaValuesLabel 1278
#define IDC_RangeMaximumLabel           1279
#define IDC_RangeMinimumLabel           1280
#define IDC_DeltaValueLabel             1281
#define IDC_Apply                       1282
#define IDC_Steps                       1283
#define IDC_Alias                       1284
#define IDC_CELL_LIST                   1291
#define IDC_COMBO_PickNameDisplay       1292
#define IDC_COMBO_PickValueDisplay      1293
#define IDC_ApplyToAll                  1295
#define IDC_ShowProperties              1297
#define IDC_EDIT1                       1300
#define IDC_EDIT_FXAlias                1300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1301
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
